name = "pip3queak/nicepoll-ak"
version = "0.0.0"
compiler = "v1.1.13"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'pip3queak/nicepoll-ak'"

[repository]
user = "pip3queak"
project = "nicepoll-ak"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
